version: '3'

services:
  gateway_nginx:
    container_name: gateway_nginx
    environment:
      - NGINX_PORT=80
    image: nginx:1.23.1
    ports:
      - '8080:80'
    volumes:
      - ./gateway-nginx:/etc/nginx/templates

  service_stubby:
    container_name: service_stubby
    command: npm run start-docker
    image: node:18.7.0-bullseye-slim
    ports:
      - '8882:8882'
    volumes:
      - ../packages/service-stubby:/app:ro
      - ../node_modules:/node_modules:ro
    working_dir: /app

  # database_postgres:
  #   container_name: database_postgres
  #   environment:
  #     PGDATA: /var/lib/postgresql/data
  #     POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
  #     POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #     POSTGRES_USER: ${POSTGRES_USER:-root}
  #   image: postgres:14.2-alpine3.15
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   volumes:
  #     - ../volumes/postgres:/var/lib/postgresql/data

  # boilerplate_nestjs:
  #   container_name: boilerplate_nestjs
  #   command: npm run start-docker
  #   build:
  #     context: ../packages/boilerplate-nestjs
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - POSTGRES_DB
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_PORT
  #     - POSTGRES_USER
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ../packages/boilerplate-nestjs:/app:cached
  #     - ../.vscode:/app/.vscode
  #     - /app/node_modules
  #   depends_on:
  #     - database_postgres

  # boilerplate_apollo:
  #   container_name: boilerplate_apollo
  #   command: npm run start-docker
  #   build:
  #     context: ../packages/boilerplate-apollo
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - POSTGRES_DB
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_PORT
  #     - POSTGRES_USER
  #   ports:
  #     - "4001:4001"
  #   volumes:
  #     - ../packages/boilerplate-apollo:/app:cached
  #     - ../.vscode:/app/.vscode
  #     - /app/node_modules
  #   depends_on:
  #     - database_postgres
