version: '3'

# Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
# (Adding the "ports" property to this file will not forward from a Codespace.)

services:
  gateway:
    container_name: gateway
    image: nginx:1.23.1
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - '8080:80'
    environment:
      - NGINX_PORT=80

  service_stubby:
    container_name: service_stubby
    command: npm run start:docker
    depends_on:
      - workspace
    image: node:18.7.0-bullseye-slim
    ports:
      - '8882:8882'
    volumes:
      - ../packages/service-stubby:/app:ro
      - ../node_modules:/node_modules:ro
    working_dir: /app

  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UPGRADE_PACKAGES: 'true'
    command: sleep infinity
    container_name: workspace
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace
      - ../volumes/.ssh:/home/vscode/.ssh

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

  # database_postgres:
  #   container_name: database_postgres
  #   environment:
  #     PGDATA: /var/lib/postgresql/data
  #     POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
  #     POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #     POSTGRES_USER: ${POSTGRES_USER:-root}
  #   image: postgres:14.2-alpine3.15
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   volumes:
  #     - ../volumes/postgres:/var/lib/postgresql/data

  # boilerplate_nestjs:
  #   container_name: boilerplate_nestjs
  #   command: npm run start:docker
  #   build:
  #     context: ../packages/boilerplate-nestjs
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - POSTGRES_DB
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_PORT
  #     - POSTGRES_USER
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ../packages/boilerplate-nestjs:/app:cached
  #     - ../.vscode:/app/.vscode
  #     - /app/node_modules
  #   depends_on:
  #     - database_postgres

  # boilerplate_apollo:
  #   container_name: boilerplate_apollo
  #   command: npm run start:docker
  #   build:
  #     context: ../packages/boilerplate-apollo
  #     dockerfile: ./Dockerfile
  #   environment:
  #     - POSTGRES_DB
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_PORT
  #     - POSTGRES_USER
  #   ports:
  #     - "4001:4001"
  #   volumes:
  #     - ../packages/boilerplate-apollo:/app:cached
  #     - ../.vscode:/app/.vscode
  #     - /app/node_modules
  #   depends_on:
  #     - database_postgres
